backend:
  name: git-gateway
  branch: main

media_folder: "resources/uploads"
public_folder: "/resources/uploads"

collections:
  - name: "layers"
    label: "Data Layer"
    folder: "layers"
    create: true
    extension: "geojson"
    format: "json"
    fields:
      - { name: "title", label: "Judul", widget: "string" }
      - { name: "body", label: "Konten GeoJSON", widget: "code", default_language: "json" }
